
#pragma config(Sensor, dgtl1,  bump1,          sensorTouch)
#pragma config(Sensor, dgtl2,  bump2,          sensorTouch)
#pragma config(Sensor, dgtl3,  bump3,          sensorTouch)
#pragma config(Sensor, dgtl4,  sonar1,         sensorSONAR_cm)
#pragma config(Sensor, dgtl6,  sonar2,         sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  sonar3,         sensorSONAR_cm)
#pragma config(Sensor, dgtl10, floor1,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, floor2,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, floor3,         sensorLEDtoVCC)
#pragma config(Motor,  port2,           motor1,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void Light(){
	//function to turn on lights based on sonar readings
	if(SensorValue[sonar1]<10 && SensorValue[sonar1]>0){
		turnLEDOn(floor1);
		turnLEDOff(floor2);
		turnLEDOff(floor3);
		}	else if(SensorValue[sonar2]<10 && SensorValue[sonar2]>0){
		turnLEDOn(floor2);
		turnLEDOff(floor1);
		turnLEDOff(floor3);
		}	else{
		turnLEDOn(floor3);
		turnLEDOff(floor2);
		turnLEDOff(floor1);
	}
}

task main()
{
	//variables
	int current=1;
	bool from1to2 = false;
	bool from1to3 = false;
	bool from2to1 = false;
	bool from2to3 = false;
	bool from3to2 = false;
	bool from3to1 = false;
	while(true)
	{

		Light(); //calls light function

		//Checks what thecurrent floor is and sets that to current
		if(SensorValue[sonar1]<10 && SensorValue[sonar1]>0)
		{
			current=1;
		}
		else if(SensorValue[sonar2]<10 && SensorValue[sonar2]>0)
		{
			current=2;
		}
		else if(SensorValue[sonar3]<10 && SensorValue[sonar3]>0)
		{
			current=3;
		}

		//All the combinations of floors in if statements to move the elevator
		if(from1to2)
		{
			if(current!=2){
				startMotor(motor1,63);
				}else{
				wait(0.5);
				stopMotor(motor1);
				from1to2=false;
			}
		}
		if(from1to3)
		{
			if(current!=3){
				startMotor(motor1,63);
				}else{
				wait(0.5);
				stopMotor(motor1);
				from1to3=false;
			}
		}
		if(from2to1)
		{
			if(current!=1){
				startMotor(motor1,-63);
				}else{
				wait(0.5);
				stopMotor(motor1);
				from2to1=false;
			}
		}
		if(from2to3)
		{
			if(current!=3){
				startMotor(motor1,63);
				}else{
				wait(0.5);
				stopMotor(motor1);
				from2to3=false;
			}
		}
		if(from3to2)
		{
			if(current!=2){
				startMotor(motor1,-63);
				}else{
				wait(0.5);
				stopMotor(motor1);
				from3to2=false;
			}
		}
		if(from3to1)
		{
			if(current!=1){
				startMotor(motor1,-63);
				}else{
				wait(0.5);
				stopMotor(motor1);
				from3to1=false;
			}
		}
	//Checks what bump switch was pressed and then calls respective floor combo statement
		if(SensorValue[bump2]==1)
		{
			if(current==1)
			{
				from1to2=true;
			}
			else if(current==3)
			{
				from3to2=true;
			}
		}
		else if(SensorValue[bump1]==1)
		{
			if(current==2)
			{
				from2to1=true;
			}
			else if(current==3)
			{
				from3to1=true;
			}
		}
		else if(SensorValue[bump3]==1)
		{
			if(current==1)
			{
				from1to3=true;
			}
			else if(current==2)
			{
				from2to3=true;
			}
		}
	}
}
